### ISSUE TITLE
Improve layout 

### ISSUE THREAD

**Issue by oneminot** [philsawicki/GoogleAnalytics-WebTester#1]
![2015-07-07 18_01_36-google analytics web tester by philippe sawicki](https://cloud.githubusercontent.com/assets/9433081/8559437/7fe3bd10-24d2-11e5-96cb-16305b362240.png)

I think we can improve the layout of this website. 

As tested: Chrome Version 44.0.2403.61 beta-m (64-bit) 

Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.61 Safari/537.36

**Comment by philsawicki** [comment]
Hi! Thanks for your report.

I tried to reproduce this issue using a similar environment, but everything looks good from here. As far as I can tell, everything is working as expected on multiple devices, browsers and networks.

From the screenshot you provided, it seems like the CSS failed to load. Maybe something related to the way Github serves/caches content when under load? It seems to have happened right after Google Analytics mentionned the tool on their channels:

* https://twitter.com/googleanalytics/status/618531965784829952 
* https://plus.google.com/u/0/+GoogleAnalytics/posts/acLdTQmCJrR

Are you still seeing the same output, even after refreshing your cache? Are there any JavaScript errors logged in the console?
